// WidgetsGallery/Demos/Popup/Overview/React/EmployeeItem.js
import React from 'react';

import { Button } from 'devextreme-react/button';

export class EmployeeItem extends React.Component {

  constructor(props) {
    super(props);

    this.showInfo = () => this.props.showInfo(props.employee);
  }

  render() {
    return (
      <React.Fragment>
        <img src={this.props.employee.Picture} /><br />
        <i>{this.props.employee.FirstName} {this.props.employee.LastName}</i><br />
        <Button
          className={'button-info'}
          text={'Details'}
          onClick={this.showInfo}
        />
      </React.Fragment>
    );
  }
}

// WidgetsGallery/Demos/Popup/Overview/Vue/EmployeeItem.vue
<template>
  <li>
    <img :src="employee.Picture"><br>
    <i>{{ employee.FirstName }} {{ employee.LastName }}</i><br>
    <dx-button
      :on-click="showEmployeeInfo"
      class="button-info"
      text="Details"
    />
  </li>
</template>
<script>
import { DxButton } from 'devextreme-vue/button';

export default {
  components: {
    DxButton
  },

  props: {
    employee: {
      type: Object,
      required: true,
      default: () => ({})
    },
    showInfo: {
      type: Function,
      required: true,
      default: () => {}
    }
  },

  methods: {
    showEmployeeInfo() {
      this.showInfo(this.employee);
    }
  }
};
</script>
