// WidgetsGallery/Demos/FilterBuilder/WithList/React/CustomItem.js
import React from 'react';

const currencyFormatter = new Intl.NumberFormat('en-US', {
  style: 'currency',
  currency: 'USD',
  minimumFractionDigits: 0,
  maximumFractionDigits: 0
});

export default function CustomItem(item) {
  return (
    <div className={'product'}>
      <img src={item.ImageSrc} />
      <div>{item.Name}</div>
      <div className={'price'}>{currencyFormatter.format(item.Price)}</div>
    </div>
  );
}

// WidgetsGallery/Demos/FilterBuilder/WithList/Vue/CustomItem.vue
<template>
  <div>
    <div class="product">
      <img :src="item.ImageSrc">
      <div>{{ item.Name }}</div>
      <div class="price">{{ item.Price | currency }}</div>
    </div>
  </div>
</template>
<script>

const currencyFormatter = new Intl.NumberFormat('en-US', {
  style: 'currency',
  currency: 'USD',
  minimumFractionDigits: 0,
  maximumFractionDigits: 0
});

export default {
  filters: {
    currency(data) {
      return currencyFormatter.format(data);
    }
  },
  props: {
    item: {
      type: Object,
      default: () => {}
    }
  },
};
</script>
<style scoped>
.product {
    height: 65px;
}

.product > img {
    height: 100%;
    float: left;
}

.product > div {
    padding-left: 10px;
    vertical-align: top;
    line-height: 65px;
    font-size: 15px;
    float: left;
}

.product > div.price {
    float: right;
    font-size: 18px;
}
</style>
