// WidgetsGallery/Demos/SelectBox/Overview/React/Field.js
import React from 'react';
import { TextBox } from 'devextreme-react';

export default function Field(data) {
  return (
    <div className={'custom-item'}>
      <img src={data.ImageSrc} />
      <TextBox className={'product-name'}
        defaultValue={data.Name}
        readOnly={true} />
    </div>
  );
}

// WidgetsGallery/Demos/SelectBox/Overview/Vue/Field.vue
<template>
  <div class="custom-item">
    <img :src="fieldData.ImageSrc">
    <dx-text-box
      :value="fieldData.Name"
      :read-only="true"
      class="product-name"
    />
  </div>
</template>
<script>
import { DxTextBox } from 'devextreme-vue';

export default {
  components: {
    DxTextBox
  },
  props: {
    fieldData: {
      type: Object,
      default: () => {}
    }
  }
};
</script>
