// WidgetsGallery/Demos/DataGrid/CellCustomization/React/ChartCell.js
import React from 'react';
import Sparkline, { Size, Tooltip } from 'devextreme-react/sparkline';

export default function ChartCell(cellData) {
  return (
    <div className={'chart-cell'}>
      <Sparkline
        dataSource={cellData.data.dayClose}
        argumentField={'date'}
        valueField={'close'}
        type={'line'}
        showMinMax={true}
        minColor={'#f00'}
        maxColor={'#2ab71b'}
        pointSize={6}>
        <Size width={290} height={40} />
        <Tooltip enabled={false} />
      </Sparkline>
    </div>
  );
}

// WidgetsGallery/Demos/DataGrid/CellCustomization/Vue/ChartCell.vue
<template>
  <div class="chart-cell">
    <dx-sparkline
      :data-source="cellData"
      :show-min-max="true"
      :point-size="6"
      argument-field="date"
      value-field="close"
      type="line"
      min-color="#f00"
      max-color="#2ab71b"
    >
      <dx-size
        :width="290"
        :height="40"
      />
      <dx-tooltip :enabled="false"/>
    </dx-sparkline>
  </div>
</template>
<script>
import {
  DxSparkline,
  DxSize,
  DxTooltip
} from 'devextreme-vue/sparkline';

export default {
  components: {
    DxSparkline,
    DxSize,
    DxTooltip
  },
  props: {
    cellData: {
      type: Array,
      default: () => []
    }
  }
};
</script>
