// WidgetsGallery/Demos/Drawer/LeftOrRightPosition/React/NavigationList.js
import React from 'react';

import List from 'devextreme-react/list.js';
import { navigation } from './data.js';

class NavigationList extends React.PureComponent {
  render() {
    return (
      <div className={'list'}>
        <List
          dataSource={navigation}
          hoverStateEnabled={false}
          activeStateEnabled={false}
          focusStateEnabled={false}
          elementAttr={{ class: 'panel-list dx-theme-accent-as-background-color' }}
          width={200} />
      </div>
    );
  }
}

export default NavigationList;

// WidgetsGallery/Demos/Drawer/LeftOrRightPosition/Vue/NavigationList.vue
<template>
  <div>
    <dx-list
      :data-source="navigation"
      :active-state-enabled="false"
      :hover-state-enabled="false"
      :focus-state-enabled="false"
      class="panel-list dx-theme-accent-as-background-color"
      width="200"
    />
  </div>
</template>
<script>
import { DxList } from 'devextreme-vue/list';
import { navigation } from './data.js';

export default {
  components: {
    DxList
  },
  data() {
    return {
      navigation
    };
  }
};
</script>
