// WidgetsGallery/Demos/DataGrid/WebAPIService/React/MasterDetailGrid.js
import React from 'react';
import DataGrid from 'devextreme-react/data-grid';

import { createStore } from 'devextreme-aspnet-data-nojquery';

const url = 'https://js.devexpress.com/Demos/Mvc/api/DataGridWebApi';

const getMasterDetailGridDataSource = (id) => {
  return {
    store: createStore({
      loadUrl: `${url}/OrderDetails`,
      loadParams: { orderID: id },
      onBeforeSend: (method, ajaxOptions) => {
        ajaxOptions.xhrFields = { withCredentials: true };
      }
    })
  };
};

class MasterDetailGrid extends React.Component {
  constructor(props) {
    super(props);
    this.dataSource = getMasterDetailGridDataSource(props.dxkey);
  }
  render() {
    return (
      <DataGrid
        dataSource={this.dataSource}
        showBorders={true}
      />
    );
  }
}

export default MasterDetailGrid;

// WidgetsGallery/Demos/DataGrid/WebAPIService/Vue/MasterDetailGrid.vue
<template>
  <dx-data-grid
    :data-source="dataSource"
    :show-borders="true"
  />
</template>

<script>
import DxDataGrid from 'devextreme-vue/data-grid';
import { createStore } from 'devextreme-aspnet-data-nojquery';

const getMasterDetailGridDataSource = (id, url) => {
  return {
    store: createStore({
      loadUrl: `${url}/OrderDetails`,
      loadParams: { orderID: id },
      onBeforeSend: (method, ajaxOptions) => {
        ajaxOptions.xhrFields = { withCredentials: true };
      }
    })
  };
};

export default {
  components: { DxDataGrid },
  props: {
    id: {
      type: Number,
      default: () => 0
    },
    url: {
      type: String,
      default: () => ''
    }
  },
  data() {
    return {
      dataSource: getMasterDetailGridDataSource(this.id, this.url)
    };
  }
};
</script>
