// WidgetsGallery/Demos/List/WebAPI/React/ProductInfo.js
﻿import React from 'react';

const currencyFormatter = new Intl.NumberFormat('en-US', {
  style: 'currency',
  currency: 'USD',
  minimumFractionDigits: 2,
  maximumFractionDigits: 2
});

export default function ProductInfo(item) {
  return (
    <React.Fragment>
      <div>{item.CategoryName}</div>
      <div>{item.ProductName}</div>
      <b className={'price'}>{currencyFormatter.format(item.UnitPrice)}</b>
    </React.Fragment>
  );
}

// WidgetsGallery/Demos/List/WebAPI/Vue/ProductInfo.vue
<template>
  <div>
    <div>{{ item.CategoryName }}</div>
    <div>{{ item.ProductName }}</div>
    <b class="price">{{ item.UnitPrice | currency }}</b>
  </div>
</template>
<script>

const currencyFormatter = new Intl.NumberFormat('en-US', {
  style: 'currency',
  currency: 'USD',
  minimumFractionDigits: 2,
  maximumFractionDigits: 2
});

export default {
  filters: {
    currency(data) {
      return currencyFormatter.format(data);
    }
  },
  props: {
    item: {
      type: Object,
      default: () => {}
    }
  },
};
</script>
